---
kind: pipeline
type: docker
name: tracerBullets
platform:
  arch: arm64
concurrency:
  limit: 1
trigger:
  branch:
    - master

environment:
  STACKROCK_API_KEY:
    from_secret: STACKROCK_API_KEY
  BUCKET:
    from_secret: BUCKET
  AWS_REGION:
    from_secret: AWS_REGION
  AWS_ACCESS_KEY_ID:
    from_secret: AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY:
    from_secret: AWS_SECRET_ACCESS_KEY

steps:
  - name: yarn install
    commands:
      - yarn install --pure-lockfile

  - name: thumbnail tracerBullet
    environment:
      INPUT_KEY:
        from_secret: THUMBNAIL_INPUT_KEY
      OUTPUT_KEY:
        from_secret: THUMBNAIL_OUTPUT_KEY
    commands:
      - ./node_modules/.bin/ts-node tracerBullet/thumbnail.ts

  - name: summary tracerBullet
    environment:
      INPUT_KEY:
        from_secret: SUMMARY_INPUT_KEY
      OUTPUT_KEY:
        from_secret: SUMMARY_OUTPUT_KEY
    commands:
      - ./node_modules/.bin/ts-node tracerBullet/summary.ts

  - name: transcode tracerBullet
    environment:
      INPUT_KEY:
        from_secret: TRANSCODE_INPUT_KEY
      OUTPUT_KEY:
        from_secret: TRANSCODE_OUTPUT_KEY
    commands:
      - ./node_modules/.bin/ts-node tracerBullet/transcode.ts
